
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sik.ctarpbj1bcrz.ap-northeast-2.rds.amazonaws.com:3306/sobibuffer
    username: root
    password: root0828
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
